### ISSUE TITLE
Running JavaScript on Windows 10 doesn't work if directories have spaces

### ISSUE THREAD

**Issue by Raymond427** [atom-community/atom-script#1455]
After I updated to the latest version of this package I noticed that when I run my javascript files I was getting

  ```
C:\Users\USERNAME\.atom\packages\script\node_modules\.bin\babel --filename C:\Users\USERNAME\.atom\packages\script\node_modules\.bin\babel < C:\Users\USERNAME\Documents\Practice Problems\sortListings.js| node
The system cannot find the file specified
  ```

This wasn't an issue with previous versions of script for me.

After looking into it further, I realized that the package works fine if none of the directories in the path to the script have spaces. When there are spaces in any of the parent directories, script can't find the file.

I recommend putting quotes around directories with spaces in them.

Let me know if anyone else has this problem, I don't think it's just something wrong with my machine but I'm not sure.

**Comment by danielbayley** [comment]
The previous approach called `babel-node` directly, which was complicating matters for everybody because you had to configure babel etc for every project just for run script to work, or worse set it up globally. So I altered it to instead pipe `|` the output of `babel` directly into `node`, using the `--filename` option to point babel back at this package so that it would use the preconfigured setup and find the necessary dependencies so that it would _just work_, and as a bonus also work for running CoffeeScript.

I don't use Windows so I'm not familiar with the ins-and-outs of file path quoting there. I did test the last fix on a Windows VM, but I guess not with spaces in the file path… I've also moved over to using _Hydrogen_ so am even less inclined to deal with Windows again.

@Raymond427 If you want to fix this, it should be a fairly easy PR if you are already familiar with Windows to test… The relevant parts of the code are [here](https://github.com/rgbkrk/atom-script/blob/master/lib/grammars/javascript.js#L9-L10) and [here](https://github.com/rgbkrk/atom-script/blob/master/lib/grammar-utils.js#L57-L62).

**Comment by Raymond427** [comment]
Hey @danielbayley, thanks for the info, I've made a PR for a patch here https://github.com/rgbkrk/atom-script/pull/1459

This is my first time really contributing to open source projects on here, so let me know if you'd like some changes.

Thanks

**Comment by WKDavid** [comment]
Thank you @Raymond427!!! I finally made Script package in Atom work for JavaScript, by simply deleting a space in a directory name! I have Atom 1.23.3 x64 running on Windows 10 and Ctrl+Shift+B constantly returned "The system cannot find the file specified.", so it's definitely not just your machine. I've tried so many different methods and nothing worked. I think it's just a  glitch.  It was never a problem to run a Python script with spaces in folder names.

**Comment by EbrahimKaram** [comment]
> Thanks @Raymond427 for all the things you mentioned , i am also having the same problem but in my case the 'username' of my PC contains space and after a bit of search i found that in WINDOWS10 you can't change the name of this folder without deleting the old user and adding the new one. I don't know what to do now. I'll be thankful to you if you can suggest me any alternative for "script" or any other solution if you have any.

Hey Raymond 
I recently installed `Process Palette` and it works fine. It needs a bit of tinkering to set the command to run node. but the documentation is adequate
