### ISSUE TITLE
Output of python in atom is incorrect, how can I solve this issue? Thanks

### ISSUE THREAD

**Issue by BakhytzhanZZ** [atom-community/atom-script#1891]
"python" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
[Finished in 0.194s]

**Comment by joshisanonymous** [comment]
I came here because I've come across this same issue.

Using Python 3.7, if I do `print("troisième")` at the console (in PowerShell), the `è` prints correctly, but running this same code with script in Atom (making sure to use Python 3 instead of 2) returns the question mark for `è`, even though the character shows up correctly everywhere else in Atom and the encoding for the document is set to UTF-8.

I wouldn't be surprised if this is just a setting issue for script and not a bug at all, but I can't find anything in the settings about encodings or fonts.

**Comment by crazytelli** [comment]
I'm having this same problem. print('maçã') gives output "ma��"

**Comment by YDum** [comment]
The problem has been discussed in [Atom's GitHub](https://github.com/atom-community/atom-script/issues/214), apparently the output in the "console" is in cp1252 in windows, and not in utf-8.
I don't know whether the problem can or should be handled in atom-script, but a solution would be great.
